name: ${PROJECT_NAME}
services:
  firstservice:
    image: firstservice
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    env_file: .env
    deploy:
      replicas: 2
    ports:
      - "5029-5030:8080"