name: ${PROJECT_NAME}

x-service-dependencies: &service-dependencies
  - first-service
  - second-service

services:
  first-service:
    image: first-service
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    networks:
      - app_network

  second-service:
    image: second-service
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    networks:
      - app_network

  balancer:
    image: balancer
    build:
      context: .
      dockerfile: Balancer/Dockerfile
    env_file: .env
    ports:
      - "5049:8080"
    depends_on: *service-dependencies
    networks:
      - app_network

networks:
  app_network:
    driver: bridge