name: ${PROJECT_NAME}

x-service-dependencies: &service-dependencies
  - first-service
  - second-service
  - mongo
  - storage

services:
  first-service:
    image: first-service
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    depends_on:
      - mongo
      - storage
    networks:
      - app_network

  second-service:
    image: second-service
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    depends_on:
      - mongo
      - storage
    networks:
      - app_network

  balancer:
    image: balancer
    build:
      context: .
      dockerfile: Balancer/Dockerfile
    env_file: .env
    ports:
      - "5049:8080"
    depends_on: *service-dependencies
    networks:
      - app_network

  storage:
    image: storage
    build:
      context: .
      dockerfile: Storage/Dockerfile
    env_file: .env
    ports:
      - "5050:8080"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data: