name: ${PROJECT_NAME}
services:
  first-service:
    image: first-service
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    ports:
      - "${FIRST_SERVICE_MIN_PORT}-${FIRST_SERVICE_MAX_PORT}:8080"
        
  second-service:
    image: second-service
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    ports:
      - "${SECOND_SERVICE_MIN_PORT}-${SECOND_SERVICE_MAX_PORT}:8080"
  
  balancer:
    image: balancer
    build:
        context: .
        dockerfile: Balancer/Dockerfile
    ports:
      - "5049:5049"