name: ${PROJECT_NAME}
services:
  first-service:
    image: first-service
    build:
      context: .
      dockerfile: FirstService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    ports:
      - "${FIRST_SERVICE_MIN_PORT}-${FIRST_SERVICE_MAX_PORT}:8080"
    depends_on:
      - second-service
      - mongo
      - storage
        
  second-service:
    image: second-service
    build:
      context: .
      dockerfile: SecondService/Dockerfile
    env_file: .env
    deploy:
      replicas: 5
    ports:
      - "${SECOND_SERVICE_MIN_PORT}-${SECOND_SERVICE_MAX_PORT}:8080"
    depends_on:
      - mongo
      - storage
  
  balancer:
    image: balancer
    build:
        context: .
        dockerfile: Balancer/Dockerfile
    ports:
      - "5049:5049"
    depends_on:
      - first-service
      - second-service
      - mongo
      - storage
  
  storage:
    image: storage
    build:
      context: .
      dockerfile: Storage/Dockerfile
    env_file: .env
    ports:
      - "5050:8080"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
        
volumes:
  mongodb_data: